# Generated by Django 5.1.4 on 2025-01-04 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
